/* Gateway login remains in IBKR. This surface has no password or order fields. */
(() => {
 let gateway={state:'disconnected',ready:false,accountCount:0},contracts=new Map(),clientId=71,message='',target=null;
 const send=(action,extra={})=>{if(liveSocket?.readyState===1)liveSocket.send(JSON.stringify({ibkr:{action,...extra}}));else notify('Local chart service is offline.');};
 function el(tag,text){const n=document.createElement(tag);if(text)n.textContent=text;return n;}
 function render(){if(!target?.isConnected)return;target.replaceChildren();const status=el('p',gateway.state.toUpperCase()+' · '+gateway.accountCount+' gateway account(s)');status.className='connection-state';target.append(status,el('p',message||'Sign in through your own TWS / IB Gateway. Enable its socket API and Read-Only API setting. No broker credentials enter Alpharch.'));
 if(!gateway.ready){const form=el('form'),port=el('select');port.id='ibkrPort';port.setAttribute('aria-label','Local IBKR API port');for(const[value,label]of[[7497,'Default TWS paper port · 7497'],[7496,'Default TWS live port · 7496'],[4002,'Default Gateway paper port · 4002'],[4001,'Default Gateway live port · 4001']]){const option=el('option',label);option.value=value;port.append(option);}const custom=el('input');custom.type='number';custom.min=1;custom.max=65535;custom.id='ibkrCustomPort';custom.placeholder='Custom local port (optional)';custom.setAttribute('aria-label','Custom local IBKR API port');const id=el('input');id.type='number';id.min=1;id.max=2147483647;id.value=clientId;id.id='ibkrClientId';id.setAttribute('aria-label','Unique IBKR API client ID');const label=el('label','Unique API client ID');label.className='field';label.append(id);const button=el('button','Connect local gateway');button.className='primary';form.append(port,custom,label,button,el('p','Ports are configurable. Selecting a port does not verify a live or paper account environment.'));form.onsubmit=e=>{e.preventDefault();clientId=+id.value;send('connect',{port:custom.value?+custom.value:+port.value,clientId});};target.append(form);}
 else{const form=el('form');form.className='broker-search';for(const[id,placeholder,value]of[['ibkrSymbol','Futures symbol','NQ'],['ibkrExchange','Exchange','CME'],['ibkrCurrency','Currency','USD'],['ibkrExpiry','Expiry YYYYMM (optional)','']]){const input=el('input');input.id=id;input.placeholder=placeholder;input.setAttribute('aria-label',placeholder);input.value=value;input.maxLength=id==='ibkrExpiry'?8:16;form.append(input);}const button=el('button','Find dated contracts');button.className='primary';form.append(button);form.onsubmit=e=>{e.preventDefault();contracts.clear();send('search',{symbol:$('ibkrSymbol').value.trim().toUpperCase(),exchange:$('ibkrExchange').value.trim().toUpperCase(),currency:$('ibkrCurrency').value.trim().toUpperCase(),expiry:$('ibkrExpiry').value.trim()});};target.append(form);const list=el('div');list.id='ibkrContracts';for(const entry of contracts.values()){const c=entry.contract,b=el('button',(c.localSymbol||c.symbol)+' · '+c.exchange+' · '+c.lastTradeDateOrContractMonth+' · tick '+entry.minTick);b.className='market-row';b.onclick=()=>{if(state.charts.length>=8){notify('Remove a chart before opening another contract.');return;}send('open',{conId:c.conId,depthRows:10});};list.append(b);}target.append(list,el('p','Select an exact expiry. Tick-by-tick trades do not supply aggressor side; delta and bid/ask footprints remain unavailable. Depth is aggregated L2. Market-data subscriptions and limits apply.'));}
 const close=el('button','Disconnect gateway');close.onclick=()=>send('disconnect');target.append(close);
 }
 window.renderBrokerConnection=container=>{target=el('section');target.id='ibkrConnect';container.append(target);render();send('status');};
 window.receiveBroker=value=>{if(value.status)gateway=value.status;if(value.clientId)clientId=value.clientId;if(value.error)message=value.error;for(const event of value.events||[]){if(event.type==='state'||event.type==='error')message=event.message;if(event.type==='contract')contracts.set(event.contract.conId,event);if(event.type==='accounts')gateway.accountCount=event.accounts.length;if(event.type==='state'&&event.state!=='connected')for(const m of Object.values(liveMarkets)){if(m.provider==='ibkr'){m.connected=false;m.book={bids:[],asks:[]};m.note=event.message;}}}
 if(value.opened&&value.contract){const details=value.contract,c=details.contract,id=String(c.conId);if(!/^\d+$/.test(id)||!/^[-A-Z0-9 ._/]{1,64}$/i.test(c.localSymbol||c.symbol))return;instruments[id]={name:c.localSymbol||c.symbol,tick:+details.minTick};const chart=makeChart({asset:id,feed:'ibkr',contract:'future',ibContract:{...c,minTick:details.minTick},w:1,h:1});const existing=state.charts.find(c=>c.feed==='ibkr'&&c.asset===id);if(existing)existing.ibContract=chart.ibContract;else state.charts.push(chart);document.getElementById('connectionsDialog')?.close();renderDesk();}
 render();};
 function renderDesk(){window.renderIBDesk();}
})();
