/* Price-aligned L2 views. Missing levels remain unknown; no synthetic order counts. */
(function(root){
'use strict';
function levels(m){return{bids:new Map((m.book?.bids||[]).map(([p,q])=>[Number(p),Number(q)])),asks:new Map((m.book?.asks||[]).map(([p,q])=>[Number(p),Number(q)]))}}
function ladderRows(m,tick,count,center){const book=levels(m),bestBid=Math.max(...book.bids.keys()),bestAsk=Math.min(...book.asks.keys());if(!Number.isFinite(bestBid)||!Number.isFinite(bestAsk)||bestBid>=bestAsk||!(tick>0))return[];const mid=Number.isFinite(center)?center:(bestBid+bestAsk)/2,index=Math.round(mid/tick),top=index+Math.floor(count/2);return Array.from({length:count},(_,i)=>{const p=Number(((top-i)*tick).toPrecision(14));return{price:p,bid:book.bids.get(p)??null,ask:book.asks.get(p)??null,bestBid:p===bestBid,bestAsk:p===bestAsk,last:Number(m.last)===p}})}
function ladder(c,g,W,H){const ct=chartColors(c);const m=marketFor(c),tick=+marketTick(c),rows=ladderRows(m,tick,Math.max(1,Math.floor((H-85)/23)),c.domCenter),left=6,right=W-6,mid=W/2,col=Math.max(35,(W-115)/2);g.font='10px ui-monospace';g.fillStyle=ct.muted;g.fillText('BID SIZE',left+5,44);g.fillText('PRICE',mid-22,44);g.fillText('ASK SIZE',right-65,44);if(!rows.length){g.fillStyle=ct.accent;g.fillText('Waiting for fresh Level 2 depth',12,75);return}const max=Math.max(1,...rows.flatMap(r=>[r.bid||0,r.ask||0]));for(let i=0;i<rows.length;i++){const r=rows[i],yy=52+i*23;g.fillStyle=r.last?ChartThemes.rgba(ct.accent,.15):i%2?ct.row:ct.background;g.fillRect(left,yy,W-12,22);if(r.bid!==null){g.fillStyle=ct.buy+'35';g.fillRect(mid-55-r.bid/max*col,yy+2,r.bid/max*col,18)}if(r.ask!==null){g.fillStyle=ct.sell+'35';g.fillRect(mid+55,yy+2,r.ask/max*col,18)}g.font=(r.bestBid||r.bestAsk?'bold ':'')+'11px ui-monospace';g.textAlign='center';g.fillStyle=r.last?ct.accent:ct.text;g.fillText(price(r.price,c),mid,yy+15);g.textAlign='left';g.fillStyle=ct.buy;g.fillText(r.bid===null?'—':quantity(r.bid),left+7,yy+15);g.fillStyle=ct.sell;g.textAlign='right';g.fillText(r.ask===null?'—':quantity(r.ask),right-7,yy+15);g.textAlign='left';if(r.bestBid||r.bestAsk){g.strokeStyle=(r.bestBid?ct.buy:ct.sell)+'aa';g.strokeRect(left,yy,W-12,22)}}g.font='9px ui-monospace';g.fillStyle=ct.muted;g.fillText('L2 · '+tick+' / row · wheel scroll · Fit recenters',10,H-20);g.fillText('— = size not supplied · no order entry / MBO',10,H-7)}
function column(c,g,y,R,W,T,B){const ct=chartColors(c);const m=marketFor(c),book=levels(m),entries=[...book.bids].map(([p,q])=>({p,q,side:'buy'})).concat([...book.asks].map(([p,q])=>({p,q,side:'sell'}))).filter(r=>y(r.p)>=T&&y(r.p)<=B);const max=Math.max(1,...entries.map(r=>r.q));g.save();g.beginPath();g.rect(R,T,W-R,B-T);g.clip();g.fillStyle=ct.panel;g.fillRect(R,T,W-R,B-T);g.font='9px ui-monospace';let lastLabel=-Infinity;entries.sort((a,b)=>y(a.p)-y(b.p));for(const r of entries){const yy=y(r.p);g.fillStyle=(r.side==='buy'?ct.buy:ct.sell)+'45';g.fillRect(R+3,yy-2,r.q/max*(W-R-8),4);if(yy-lastLabel<16)continue;lastLabel=yy;g.fillStyle=ct.text;g.fillText(price(r.p,c),R+5,yy-4);g.fillStyle=r.side==='buy'?ct.buy:ct.sell;g.textAlign='right';g.fillText(quantity(r.q),W-5,yy-4);g.textAlign='left'}g.restore();g.fillStyle=ct.muted;g.font='9px ui-monospace';g.fillText('CURRENT L2',R+6,T-8)}
function wheel(c,e){const m=marketFor(c),b=m?.book?.bids?.[0],a=m?.book?.asks?.[0];if(!b||!a)return;c.domCenter=(c.domCenter??((Number(b[0])+Number(a[0]))/2))+Math.sign(e.deltaY)*+marketTick(c)*3;changed(c)}
root.DepthViews={ladderRows,ladder,column,wheel};if(typeof module!=='undefined'&&module.exports)module.exports={ladderRows};
})(globalThis);
