/* Chart-local controls. Drawing state stays with the chart; no desktop keybindings. */
(function(root){
'use strict';
const chosen=new WeakMap(),pending=new WeakMap();let flyout=null,editor=null;
const icons={grid:'<path d="M3 3h18v18H3zM3 9h18M3 15h18M9 3v18M15 3v18"/>',cursor:'<path d="M6 3l12 10-6 1-3 6z"/>',cross:'<path d="M12 2v20M2 12h20"/><circle cx="12" cy="12" r="3"/>',Lines:'<path d="M4 19L20 5"/><circle cx="4" cy="19" r="2"/><circle cx="20" cy="5" r="2"/>','Zones & channels':'<path d="M3 17L19 3M5 21L21 7"/>',Fibonacci:'<path d="M3 4h18M3 9h13M3 14h18M3 20h10"/>',Markup:'<path d="M4 18c2-15 6-15 6-6s4 9 6 0 4-9 4-6"/>',Planning:'<path d="M4 6h16M4 18h16M6 4v16M18 4v16M9 12h6"/>',magnet:'<path d="M5 4v9a7 7 0 0014 0V4h-4v9a3 3 0 01-6 0V4z"/>',eye:'<path d="M2 12q10-14 20 0-10 14-20 0z"/><circle cx="12" cy="12" r="3"/>',lock:'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V6a4 4 0 018 0v4"/>',objects:'<path d="M8 5h13M8 12h13M8 19h13M3 5h1M3 12h1M3 19h1"/>',undo:'<path d="M8 4L3 9l5 5M3 9h10a7 7 0 010 14"/>',redo:'<path d="M16 4l5 5-5 5M21 9h-10a7 7 0 000 14"/>',boxzoom:'<path d="M3 8V3h5M16 3h5v5M21 16v5h-5M8 21H3v-5"/>'};
const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n};
function button(label,icon,action){const b=el('button','draw-button');b.type='button';b.title=label;b.setAttribute('aria-label',label);b.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true">'+(icons[icon]||icons.objects)+'</svg>';b.onclick=e=>{e.stopPropagation();action(b)};return b}
function close(){flyout?.remove();flyout=null}
function choose(c,type){c.tool=type;pending.delete(c);drawingStarts.delete(c);close();refresh(c);draw(c);const def=DrawingTools.byId[type];notify(def?def.name+' · '+(def.anchors?def.anchors+' anchor'+(def.anchors>1?'s':'')+' · click the chart':'press and drag')+' · Escape cancels':type==='boxzoom'?'Click two corners to zoom.':'Cursor · drag to pan, click a drawing to select');$('chart-'+c.id)?.querySelector('canvas').focus()}
function panel(c,b,title){close();focus(c);flyout=el('div','drawing-flyout');flyout.setAttribute('role','dialog');flyout.setAttribute('aria-label',title);const h=el('div','draw-flyhead');h.append(el('strong','',title));const exit=el('button','','×');exit.setAttribute('aria-label','Close drawing menu');exit.onclick=close;h.append(exit);flyout.append(h);document.body.append(flyout);const r=b.getBoundingClientRect();flyout.style.left=Math.min(innerWidth-296,r.right+6)+'px';flyout.style.top=Math.max(8,Math.min(innerHeight-440,r.top))+'px';return flyout}
function group(c,b,name){const p=panel(c,b,name);for(const d of DrawingTools.catalog.filter(d=>d.group===name)){const row=el('button','drawing-choice');row.append(el('span','drawing-glyph',d.glyph),el('span','',d.name));row.title=d.description;row.setAttribute('aria-label',d.name);row.onclick=()=>choose(c,d.id);p.append(row)}p.querySelector('.drawing-choice')?.focus()}
function prefs(c){return {...DrawingTools.defaults,...c.drawingPrefs}}
function refresh(c){const rail=$('chart-'+c.id)?.querySelector('.drawing-rail');if(!rail)return;for(const b of rail.querySelectorAll('[data-mode]'))b.setAttribute('aria-pressed',String(b.dataset.mode===(c.tool||'cursor')));for(const b of rail.querySelectorAll('[data-group]'))b.setAttribute('aria-pressed',String(DrawingTools.byId[c.tool]?.group===b.dataset.group));for(const [name,value] of Object.entries({cross:c.crosshair!==false,magnet:prefs(c).magnet,eye:!c.drawingsHidden,lock:!!c.drawingsLocked}))rail.querySelector('[data-control="'+name+'"]')?.setAttribute('aria-pressed',String(value));rail.querySelector('[data-control="eye"]')?.setAttribute('title',c.drawingsHidden?'Show drawings':'Hide drawings');rail.querySelector('[data-control="lock"]')?.setAttribute('title',c.drawingsLocked?'Unlock all drawings':'Lock all drawings')}
function mount(c,tile){
 const rail=el('aside','drawing-rail');rail.setAttribute('role','toolbar');rail.setAttribute('aria-label','Drawing tools for '+chartName(c));rail.setAttribute('aria-orientation','vertical');
 const add=(label,icon,action,data)=>{const b=button(label,icon,()=>{focus(c);action(b)});Object.assign(b.dataset,data);rail.append(b);return b};
 add('Cursor / select (Esc)','cursor',()=>choose(c,'cursor'),{mode:'cursor'});
 add('Crosshair on / off (C)','cross',()=>{c.crosshair=c.crosshair===false;shareCursor(c,null);refresh(c);changed(c)},{control:'cross'});
 for(const groupName of ['Lines','Zones & channels','Fibonacci','Markup','Planning'])add(groupName,groupName,b=>group(c,b,groupName),{group:groupName});
 add('Zoom to box','boxzoom',()=>choose(c,'boxzoom'),{mode:'boxzoom'});
 rail.append(el('span','drawing-divider'));
 add('Magnet · snap to nearby OHLC','magnet',()=>{c.drawingPrefs={...prefs(c),magnet:!prefs(c).magnet};refresh(c);saveSoon()},{control:'magnet'});
 add('Show / hide drawings','eye',()=>{c.drawingsHidden=!c.drawingsHidden;refresh(c);changed(c)},{control:'eye'});
 add('Lock / unlock all drawings','lock',()=>{c.drawingsLocked=!c.drawingsLocked;refresh(c);changed(c)},{control:'lock'});
 add('Chart grid settings','grid',()=>IntervalUI.openGrid(c),{});
 add('Drawing objects & style','objects',()=>objects(c),{control:'objects'});
 add('Undo drawing (Ctrl+Z)','undo',()=>{undoDrawing(c);chosen.delete(c);refresh(c)},{});
 add('Redo drawing (Ctrl+Shift+Z)','redo',()=>{undoDrawing(c,true);chosen.delete(c);refresh(c)},{});
 tile.append(rail);refresh(c);
 tile.querySelector('canvas').addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey)return;const key=e.key.toLowerCase();if(key==='escape'){e.stopPropagation();choose(c,'cursor');chosen.delete(c);draw(c)}else if(key==='delete'||key==='backspace'){const d=chosen.get(c);if(d&&!c.drawingsLocked&&!d.locked){e.preventDefault();rememberDrawings(c);c.drawings=c.drawings.filter(v=>v!==d);chosen.delete(c);changed(c)}}else if({h:'hline',t:'trend',r:'rectangle',f:'fibonacci',b:'brush'}[key]){e.preventDefault();choose(c,{h:'hline',t:'trend',r:'rectangle',f:'fibonacci',b:'brush'}[key])}else if(key==='c'){e.preventDefault();rail.querySelector('[data-control="cross"]').click()}});
}
function env(c,r){return{r,tick:+marketTick(c),snap:v=>snap(v,+marketTick(c)),format:v=>price(v,c),x:p=>r.L+(timeAxis(c,p.t,p)-r.from)/r.span*r.plotW,y:p=>r.T+(r.high-p)/(r.high-r.low)*(r.B-r.T)}}
function point(c,e,r){const xx=clamp(e.offsetX,r.L,r.R),yy=clamp(e.offsetY,r.T,r.B);let axis=r.from+(xx-r.L)/r.plotW*r.span,p=r.high-(yy-r.T)/(r.B-r.T)*(r.high-r.low);if(prefs(c).magnet){const bars=barsFor(c),b=bars.find(b=>axis>=b.t&&axis<(b.end??b.t+c.tf));if(b){const nearest=['o','h','l','c'].map(k=>b[k]).sort((a,b)=>Math.abs(a-p)-Math.abs(b-p))[0];if(Math.abs(nearest-p)/(r.high-r.low)*(r.B-r.T)<=12)p=nearest}}return{...axisPoint(c,axis),p:c.feed==='ibkr'?snap(p,+marketTick(c)):Math.max(+marketTick(c),snap(p,+marketTick(c)))}}
function commit(c,d){if(!DrawingTools.valid(d,c.feed==='ibkr')){notify('Invalid anchors. Long plan: stop below entry, target above. Short plan: the reverse.');pending.delete(c);draw(c);return}rememberDrawings(c);(c.drawings??=[]).push(d);chosen.set(c,d);pending.delete(c);if(!prefs(c).repeat)c.tool='cursor';refresh(c);changed(c);if(d.type==='note')objects(c)}
function click(c,e,r){if(!c.tool||c.tool==='cursor'||e.offsetX<r.L||e.offsetX>r.R||e.offsetY<r.T||e.offsetY>r.B)return false;
 if(c.drawingsHidden){c.drawingsHidden=false;refresh(c)}if((c.drawings||[]).length>=50){notify('50 drawings on this chart · remove an object to add another.');return true}
 const p=point(c,e,r),def=DrawingTools.byId[c.tool],points=pending.get(c)||[];if(!p.t)return true;points.push(p);
 if(c.tool==='boxzoom'){if(points.length<2){pending.set(c,points);notify('Click the opposite corner · Esc cancels');return true}const a=points[0];c.until=Math.max(timeAxis(c,a.t,a),timeAxis(c,p.t,p));c.count=clamp(Math.abs(timeAxis(c,a.t,a)-timeAxis(c,p.t,p))/r.unit,1,2000);c.priceRange={low:Math.min(a.p,p.p)-+marketTick(c),high:Math.max(a.p,p.p)+ +marketTick(c)};choose(c,'cursor');changed(c);return true}
 if(!def)return false;if(!def.anchors)return true;if(points.length<def.anchors){pending.set(c,points);notify(def.name+' · click anchor '+(points.length+1)+' of '+def.anchors);draw(c);return true}
 commit(c,{type:def.id,text:def.id==='note'?'Note':'',points,style:{...prefs(c)}});return true;
}
function drag(c,event,r,canvas,hover){
 if(event.offsetX<r.L||event.offsetX>r.R||event.offsetY<r.T||event.offsetY>r.B)return false;
 const free=['brush','highlighter'].includes(c.tool);let d,hit;
 if(free){if((c.drawings||[]).length>=50)return true;if(c.drawingsHidden){c.drawingsHidden=false;refresh(c)}d={type:c.tool,text:'',points:[point(c,event,r)],style:{...prefs(c)}};pending.set(c,d.points)}else{if(c.drawingsLocked||c.drawingsHidden)return false;for(const obj of [...(c.drawings||[])].reverse()){const h=DrawingTools.hit(obj,env(c,r),{x:event.offsetX,y:event.offsetY});if(h){d=obj;hit=h;break}}chosen.delete(c);if(!d){draw(c);return false}chosen.set(c,d);draw(c)}
 const original=structuredClone(d),start=point(c,event,r),startAxis=timeAxis(c,start.t,start);let moved=false;
 canvas.setPointerCapture(event.pointerId);
 canvas.onpointermove=e=>{if(Math.hypot(e.clientX-event.clientX,e.clientY-event.clientY)<3&&!moved)return;const p=point(c,e,r);if(!p.t)return;moved=true;if(free){if(d.points.length>=128)d.points=d.points.filter((_,i)=>i===0||i%2===1);d.points.push(p);pending.set(c,d.points)}else if(hit.anchor!==null){d.points[hit.anchor]=p}else{const dt=timeAxis(c,p.t,p)-startAxis,dp=snap(p.p-start.p,+marketTick(c));d.points=original.points.map(a=>({...axisPoint(c,timeAxis(c,a.t,a)+dt),p:snap(a.p+dp,+marketTick(c))}))}draw(c)};
 const finish=e=>{canvas.onpointermove=hover;canvas.onpointerup=null;canvas.onpointercancel=null;canvas.onlostpointercapture=null;if(canvas.hasPointerCapture(event.pointerId))canvas.releasePointerCapture(event.pointerId);const cancel=e.type!=='pointerup';if(free){pending.delete(c);if(!cancel&&d.points.length>=2)commit(c,d)}else if(moved){const updated=structuredClone(d);Object.assign(d,original);if(!cancel&&DrawingTools.valid(updated,c.feed==='ibkr')){rememberDrawings(c);Object.assign(d,updated)}}changed(c)};
 canvas.onpointerup=finish;canvas.onpointercancel=finish;canvas.onlostpointercapture=finish;return true;
}
function paint(c,g,tx,y,L,R,T,B){if(c.drawingsHidden)return;const r={L,R,T,B},e={r,tick:+marketTick(c),snap:v=>snap(v,+marketTick(c)),format:v=>price(v,c),x:p=>tx(timeAxis(c,p.t,p)),y};for(const d of c.drawings||[])DrawingTools.paint(g,d,e,chosen.get(c)===d&&!c.drawingsLocked);const points=pending.get(c),def=DrawingTools.byId[c.tool];if(points?.length&&def){const p=[...points],geo=geometry.get(c);if(def.anchors&&c.mouse&&geo){const next=point(c,{offsetX:c.mouse.x,offsetY:c.mouse.y},geo);while(p.length<def.anchors)p.push(next)}if(p.length>=(def.anchors||2))DrawingTools.paint(g,{type:def.id,text:'',points:p,style:prefs(c)},e,false,true)}}
function objects(c){
 close();editor?.remove();editor=el('dialog','drawing-editor');editor.setAttribute('aria-label','Drawing objects & style');const head=el('div','modal-head');head.append(el('h1','','Drawings · '+chartName(c)));const exit=el('button','','×');exit.setAttribute('aria-label','Close drawing objects');exit.onclick=()=>editor.close();head.append(exit);editor.append(head);const body=el('div','new-body');editor.append(body);document.body.append(editor);
 const render=()=>{body.replaceChildren();const d=chosen.get(c),obj=(c.drawings||[]).includes(d)?d:null;
 const select=el('select');select.setAttribute('aria-label','Selected drawing');select.add(new Option('New drawing defaults',''));(c.drawings||[]).forEach((v,i)=>select.add(new Option((i+1)+'. '+(v.text||DrawingTools.byId[v.type].name)+(v.locked?' · locked':'')+(v.hidden?' · hidden':''),String(i))));select.value=obj?String(c.drawings.indexOf(obj)):'';select.onchange=()=>{chosen.set(c,c.drawings[+select.value]);if(select.value==='')chosen.delete(c);render();draw(c)};body.append(select);
 const form=el('form','drawing-properties');const locked=!!obj&&(c.drawingsLocked||obj.locked),style={...prefs(c),...obj?.style};const fields={};
 const field=(name,input)=>{input.setAttribute('aria-label',name);const l=el('label','');l.append(el('span','',name),input);form.append(l);return input};
 if(obj){fields.text=field('Label',Object.assign(el('input'),{value:obj.text,maxLength:80}));if(obj.points.length<=3)fields.points=obj.points.map((p,i)=>({price:field('Anchor '+(i+1)+' price',Object.assign(el('input'),{type:'text',inputMode:'decimal',value:String(p.p)})),time:field('Anchor '+(i+1)+' time UTC',Object.assign(el('input'),{type:'datetime-local',step:'0.001',value:new Date(p.t*1000).toISOString().slice(0,23)})),original:p}));}
 fields.color=field('Color',Object.assign(el('input'),{type:'color',value:style.color}));fields.width=field('Line width',Object.assign(el('input'),{type:'number',min:.5,max:6,step:.5,value:style.width}));fields.fill=field('Fill opacity',Object.assign(el('input'),{type:'number',min:0,max:.6,step:.01,value:style.fill}));const dash=el('select');['solid','dashed','dotted'].forEach(v=>dash.add(new Option(v,v)));dash.value=style.dash;fields.dash=field('Line style',dash);fields.extend=field('Extend levels / channel',Object.assign(el('input'),{type:'checkbox',checked:style.extend}));if(!obj)fields.repeat=field('Keep drawing tool active',Object.assign(el('input'),{type:'checkbox',checked:style.repeat}));
 if(obj&&DrawingTools.ratios[obj.type])fields.ratios=field('Ratios · comma separated',Object.assign(el('input'),{value:(obj.ratios||DrawingTools.ratios[obj.type]).join(', ')}));
 const status=el('p','source-note');status.setAttribute('role','status');const apply=el('button','primary',obj?'Apply to drawing':'Save drawing defaults');apply.type='submit';form.append(apply,status);if(locked){for(const n of form.querySelectorAll('input,select,button'))n.disabled=true;status.textContent='Unlock this drawing to edit its anchors or style.'}
 form.onsubmit=e=>{e.preventDefault();const s={...style,color:fields.color.value,width:+fields.width.value,fill:+fields.fill.value,dash:fields.dash.value,extend:fields.extend.checked,repeat:fields.repeat?.checked??style.repeat};if(!DrawingTools.styleValid(s)){status.textContent='Check color, line width and fill opacity.';return}if(obj){const candidate=structuredClone(obj);candidate.text=fields.text.value;candidate.style=s;if(fields.points)candidate.points=fields.points.map(f=>{const t=Date.parse(f.time.value+'Z')/1000,p={...f.original,p:snap(Number(f.price.value),+marketTick(c))};if(!f.price.value.trim())p.p=NaN;if(!Number.isFinite(t)||Math.abs(t-f.original.t)>=.001){p.t=t;delete p.eventId;delete p.eventOffset}return p});if(fields.ratios)candidate.ratios=fields.ratios.value.split(',').map(v=>v.trim()?Number(v):NaN);if(!DrawingTools.valid(candidate,c.feed==='ibkr')){status.textContent='Check exact prices, times and ratios. A long stop must be below entry; a short stop above.';return}rememberDrawings(c);Object.assign(obj,candidate)}else c.drawingPrefs=s;changed(c);refresh(c);status.textContent='Saved · prices snapped to '+marketTick(c)+' native ticks.'};body.append(form);
 if(obj){const actions=el('div','object-row');for(const [label,fn]of [[obj.hidden?'Show':'Hide',()=>{obj.hidden=!obj.hidden}],[obj.locked?'Unlock':'Lock',()=>{obj.locked=!obj.locked}],['Duplicate',()=>{if(c.drawings.length>=50)return;const copy=structuredClone(obj);copy.locked=false;c.drawings.push(copy);chosen.set(c,copy)}],['Delete',()=>{c.drawings=c.drawings.filter(v=>v!==obj);chosen.delete(c)}]]){const b=el('button','',label);b.disabled=(label==='Delete'||label==='Duplicate')&&locked||label==='Unlock'&&c.drawingsLocked;b.onclick=()=>{rememberDrawings(c);fn();render();changed(c)};actions.append(b)}body.append(actions)}const history=el('div','object-row');for(const redo of [false,true]){const b=el('button','',redo?'Redo':'Undo');b.onclick=()=>{undoDrawing(c,redo);chosen.delete(c);render()};history.append(b)}body.append(history,el('p','source-note','Select a line or handle to move it. H: level · T: trend · R: rectangle · F: Fibonacci · B: brush · C: crosshair · Esc: cursor. Drawings save with this chart. Up to 50 objects.'));
 };render();editor.showModal();
}
function editHit(c,e,r){if(c.tool&&c.tool!=='cursor')return true;const d=[...(c.drawings||[])].reverse().find(d=>DrawingTools.hit(d,env(c,r),{x:e.offsetX,y:e.offsetY}));if(!d||c.drawingsHidden)return false;chosen.set(c,d);objects(c);return true}
function init(){document.addEventListener('pointerdown',e=>{if(flyout&&!e.target.closest('.drawing-flyout,.drawing-rail'))close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){close();for(const c of state.charts){pending.delete(c);refresh(c);draw(c)}}});window.addEventListener('resize',close)}
root.DrawingUI={mount,refresh,choose,click,drag,paint,objects,editHit,init};
})(globalThis);
