/* Deterministic observations. No model invocation and no execution interface. */
(() => {
 const cache=new Map();let chartId=null;
 const dialog=document.createElement('dialog');dialog.id='insightsDialog';dialog.innerHTML=`<div class="modal-head"><div><div class="eyebrow">READ THE RECORD</div><h1 id="insightTitle">Observed market</h1></div><button class="close" aria-label="Close observations">×</button></div><div class="new-body"><div class="object-row"><button id="refreshInsights" class="primary">Refresh observations</button><label><input id="showDepthLevels" type="checkbox"> Show depth concentrations on chart</label><label><input id="includeOptions" type="checkbox"> Include Deribit options context</label></div><p id="insightScope" class="source-note">Choose Refresh to read the selected chart's captured data.</p><div id="insightFacts"></div><h3>Observed concentrations</h3><p class="source-note">Displayed orders can be cancelled. Options open interest is grouped by expiry and put/call. These observations describe supplied data; they do not predict price or describe dealer positioning.</p><div id="insightLevels"></div><h3>Session note</h3><textarea id="insightNote" rows="3" maxlength="3000" placeholder="What did you observe?" aria-label="Session note"></textarea><div class="object-row"><button id="saveInsightNote">Append note and source to journal</button><button id="exportInsights">Export observed facts</button></div><p class="source-note">Your notes stay in your local daily journal. The Desk Brain can separately narrate a saved recording through your own CLI.</p></div>`;document.body.append(dialog);
 const button=document.createElement('button');button.id='observations';button.className='primary';button.textContent='Observed market / options';document.querySelector('#toolsDialog .new-body').prepend(button);
 function selectedChart(){return state.charts.find(c=>c.id===chartId);}
 function refresh(){const c=selectedChart();if(!c||liveSocket?.readyState!==1)return;$('insightScope').textContent='Reading supplied market data…';liveSocket.send(JSON.stringify({insights:{key:c.feed+':'+c.asset,options:!!c.options}}));}
 button.onclick=()=>{chartId=toolsChart;const c=selectedChart();if(!c)return;$('toolsDialog').close();$('insightTitle').textContent=chartName(c)+' · observed';$('showDepthLevels').checked=!!c.discovery;$('includeOptions').checked=!!c.options;$('includeOptions').disabled=window.deskReplay||c.asset==='SOL';dialog.showModal();refresh();};
 dialog.querySelector('.close').onclick=()=>dialog.close();$('refreshInsights').onclick=refresh;
 $('showDepthLevels').onchange=()=>{const c=selectedChart();if(c){c.discovery=$('showDepthLevels').checked;changed(c);refresh();}};
 $('includeOptions').onchange=()=>{const c=selectedChart();if(c){c.options=$('includeOptions').checked;changed(c);refresh();}};
 function cell(tag,text){const e=document.createElement(tag);e.textContent=text;return e;}
 window.receiveInsights=value=>{cache.set(value.key,value);const c=selectedChart();state.charts.filter(c=>c.feed+':'+c.asset===value.key).forEach(draw);if(!c||c.feed+':'+c.asset!==value.key||!dialog.open)return;const f=value.facts;
 $('insightScope').textContent=f.symbol+' · '+f.source+' · '+(f.replay?'REPLAY':'LIVE CAPTURE')+' · observed '+new Date(f.asOf*1000).toISOString().replace('T',' ').slice(0,19)+' UTC. '+f.definitions.scope+(f.partial?' Capture has interruptions.':'');
 const facts=$('insightFacts');facts.replaceChildren();for(const[label,v]of [['Received trades',String(f.trades)],['Captured volume',f.volume+' '+(marketFor(c)?.quantityUnit||c.asset)],['Aggressor delta',f.delta===null?'Unavailable · side not supplied':f.delta+' '+(marketFor(c)?.quantityUnit||c.asset)],['Captured high',f.high?price(+f.high,c):'unavailable'],['Captured low',f.low?price(+f.low,c):'unavailable'],['Captured VWAP',f.vwap?price(+f.vwap,c):'unavailable']]){const row=cell('div','');row.append(cell('small',label),cell('strong',v));facts.append(row);}
 const list=$('insightLevels');list.replaceChildren();const rows=[...(f.levels||[]),...(value.options?.levels||[]).slice(0,20)];for(const level of rows){const row=cell('div','');row.className='insight-level';row.append(cell('strong',price(level.price,c)),cell('span',level.metric==='displayed_depth'?level.side+' displayed · '+quantity(level.value)+' '+c.asset:level.expiry+' · '+level.side+' · OI '+quantity(level.value)),cell('small',level.ratio.toFixed(2)+'× group median · '+level.source));list.append(row);}if(!rows.length)list.append(cell('p','No qualifying fresh concentrations in the supplied data.'));if(value.options)list.append(cell('p',value.options.source+' · '+value.options.status+' · '+value.options.definition));
 };
 window.drawObservedLevels=(c,g,y,L,R,T,B)=>{if(!c.discovery&&!c.options)return;const data=cache.get(c.feed+':'+c.asset);if(!data)return;const now=marketFor(c)?.replay?marketFor(c).replayClock:Date.now()/1000;let levels=[];if(c.discovery&&Math.abs(now-data.facts.asOf)<=15)levels.push(...data.facts.levels.slice(0,6));if(c.options&&!window.deskReplay&&data.options?.status==='receiving'&&now-data.options.fetchedAt<120)levels.push(...data.options.levels.slice(0,8));g.save();g.font='9px ui-monospace';for(const level of levels){const yy=y(level.price);if(yy<T+12||yy>B-6)continue;g.setLineDash(level.metric==='displayed_depth'?[5,5]:[2,6]);g.strokeStyle=level.metric==='displayed_depth'?'#e8c58699':'#b5a0ea88';g.fillStyle=level.metric==='displayed_depth'?'#e8c586':'#b5a0ea';g.beginPath();g.moveTo(L,yy);g.lineTo(R,yy);g.stroke();g.fillText(level.metric==='displayed_depth'?level.side.toUpperCase()+' DEPTH · '+level.ratio.toFixed(1)+'×':level.expiry+' '+level.side+' OI · '+level.ratio.toFixed(1)+'×',L+4,yy-4);}g.restore();};
 $('saveInsightNote').onclick=()=>{const c=selectedChart(),data=c&&cache.get(c.feed+':'+c.asset),note=$('insightNote').value.trim();if(!note||!data){notify('Write a note and refresh observations before saving.');return;}const f=data.facts,stamp=new Date(f.asOf*1000).toISOString(),text='['+(f.replay?'REPLAY':'LIVE CAPTURE')+' '+f.source+' '+f.symbol+' '+stamp+'] '+note+'\n  Captured '+f.trades+' trades; volume '+f.volume+' '+c.asset+'; delta '+f.delta+' '+c.asset+'; high '+f.high+'; low '+f.low+'. '+f.definitions.scope;desktopAction('journal-note',{text});$('insightNote').value='';};
 $('exportInsights').onclick=()=>{const c=selectedChart(),data=c&&cache.get(c.feed+':'+c.asset);if(!data)return;const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='alpharch-observed-'+c.asset+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 // Requests exist only while an overlay or the observation dialog is enabled.
 setInterval(()=>{if(liveSocket?.readyState!==1)return;const keys=new Set();for(const c of state.charts){if(!c.discovery&&!c.options&&(!dialog.open||chartId!==c.id))continue;const key=c.feed+':'+c.asset;if(keys.has(key))continue;keys.add(key);liveSocket.send(JSON.stringify({insights:{key,options:!!c.options&&!window.deskReplay}}));}},10000);
})();
