/* Standard intervals, typed custom values, and chart-local favorites. */
(function(root){
'use strict';
const defaults=['1m','5m','30m','1h','3h','4h','1d','1w'];let dialog=null;
const groups={'Seconds':['1s','5s','10s','15s','30s','45s'],'Minutes':['1m','2m','3m','5m','10m','15m','30m','45m'],'Hours':['1h','2h','3h','4h','6h','8h','12h'],'Days / weeks / months':['1d','2d','1w','1M','3M','6M','12M'],'Range · native ticks':['1R','10R','20R','40R','80R','100R','1000R'],'Ticks · trade count':['1T','10T','100T','500T','1000T','2000T'],'Volume · traded quantity':['100V','1000V','10000V']};
const el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n};
function favorites(c){return c.intervalFavorites||defaults}
function apply(c,input){const setting=Intervals.parse(input,+marketTick(c));Object.assign(c,setting);c.eventAxis=1;c.until=null;c.priceRange=null;geometry.delete(c);syncAggregations();fitChart(c);refresh(c);notify(chartName(c)+' · '+Intervals.label(c)+(isEvent(c)?' · captured trades':' · UTC time bars'));}
function fill(select,c,custom=true){select.replaceChildren();for(const [name,values]of Object.entries(groups)){const group=el('optgroup');group.label=name;for(const value of values)group.append(new Option(value,value));select.append(group)}const current=Intervals.label(c);if(![...select.options].some(o=>o.value===current))select.add(new Option(current,current));if(custom)select.add(new Option('Custom / favorites…','custom'));select.value=current;select.disabled=false;}
function refresh(c){const tile=$('chart-'+c.id);if(!tile)return;const select=tile.querySelector('.tf');if(select.value!==Intervals.label(c)||select.options.length<10)fill(select,c);select.title='Chart interval · '+Intervals.label(c)+' · custom sizes and favorites';const bar=tile.querySelector('.interval-shortcuts');if(!bar)return;const signature=favorites(c).join(',')+'|'+Intervals.label(c);if(bar.dataset.signature===signature)return;bar.dataset.signature=signature;bar.replaceChildren();for(const value of favorites(c)){const b=el('button',value);b.type='button';b.setAttribute('aria-label','Set interval '+value);b.setAttribute('aria-pressed',String(value===Intervals.label(c)));b.onclick=()=>{focus(c);apply(c,value)};bar.append(b)}}
function mount(c,tile){const bar=el('div');bar.className='interval-shortcuts';bar.setAttribute('role','group');bar.setAttribute('aria-label','Favorite chart intervals');tile.querySelector('.chart-tools').append(bar);const history=el('button','History');history.type='button';history.className='history-control';history.setAttribute('aria-label','History / data for this chart');history.title='History / data · this chart only';history.onclick=()=>openHistory(c);tile.querySelector('.chart-tools').insertBefore(history,bar);const select=tile.querySelector('.tf');fill(select,c);select.onchange=()=>{if(select.value==='custom'){fill(select,c);open(c)}else apply(c,select.value)};refresh(c);tile.querySelector('canvas').addEventListener('keydown',e=>{if(!e.ctrlKey&&!e.metaKey&&!e.altKey&&/^[1-9]$/.test(e.key)){e.preventDefault();open(c,e.key)}})}
function open(c,initial=''){
 dialog?.remove();dialog=el('dialog');dialog.className='interval-picker';dialog.setAttribute('aria-label','Chart interval');const head=el('div');head.className='modal-head';head.append(el('h1','Chart interval · '+chartName(c)));const close=el('button','×');close.setAttribute('aria-label','Close interval picker');close.onclick=()=>dialog.close();head.append(close);dialog.append(head);const body=el('div');body.className='new-body';dialog.append(body);
 const form=el('form');form.className='interval-input';const input=el('input');input.setAttribute('aria-label','Custom interval');input.placeholder='Type an interval, e.g. 3h or 40R';input.value=initial;input.maxLength=40;const go=el('button','Apply');go.className='primary';form.append(input,go);body.append(form);const error=el('p');error.className='source-note';error.setAttribute('role','status');body.append(error);
 form.onsubmit=e=>{e.preventDefault();try{apply(c,input.value);dialog.close()}catch(err){error.textContent=err.message}};
 const legend=el('p','s seconds · m minutes · h hours · d days · w weeks · M months\nR range ticks · P range points · T trade count · V volume');legend.className='interval-examples';legend.style.whiteSpace='pre-line';body.append(legend);
 const pin=el('button','☆ Add typed interval to favorites');pin.type='button';pin.onclick=()=>{try{const value=Intervals.label(Intervals.parse(input.value,+marketTick(c)));if(favorites(c).includes(value)){error.textContent=value+' is already a favorite.';return}if(favorites(c).length>=16){error.textContent='Up to 16 favorites · remove one below first.';return}c.intervalFavorites=[...favorites(c),value];renderFavorites();refresh(c);saveSoon();error.textContent=value+' added to the chart toolbar.'}catch(err){error.textContent=err.message}};body.append(pin);
 const favoriteArea=el('div');favoriteArea.className='interval-grid';body.append(favoriteArea);function renderFavorites(){favoriteArea.replaceChildren();for(const value of favorites(c)){const b=el('button',value+' ×');b.setAttribute('aria-label','Remove favorite '+value);b.onclick=()=>{c.intervalFavorites=favorites(c).filter(v=>v!==value);renderFavorites();refresh(c);saveSoon()};favoriteArea.append(b)}}renderFavorites();
 for(const [name,values]of Object.entries(groups)){body.append(el('h3',name));const grid=el('div');grid.className='interval-grid';for(const value of values){const b=el('button',value);b.type='button';b.onclick=()=>{apply(c,value);dialog.close()};grid.append(b)}body.append(grid)}
 const note=el('p','Time bars use UTC boundaries; weeks start Monday and months follow the calendar. These are not CME RTH/ETH session templates. History depends on the feed; seconds, range, tick and volume use retained captured trades. Range closes when high–low reaches the chosen native ticks; a gap can exceed it. No artificial gap bars. Volume uses the feed’s quantity units.');note.className='interval-source';body.append(note);document.body.append(dialog);dialog.showModal();input.focus();
}
function openGrid(c){
 dialog?.remove();dialog=el('dialog');dialog.className='interval-picker';dialog.setAttribute('aria-label','Chart grid settings');const head=el('div');head.className='modal-head';head.append(el('h1','Grid · '+chartName(c)));const exit=el('button','×');exit.setAttribute('aria-label','Close grid settings');exit.onclick=()=>dialog.close();head.append(exit);dialog.append(head);const form=el('form');form.className='new-body drawing-properties';const g={density:'normal',contrast:appearance().grid,visible:true,minor:true,...c.grid};const field=(name,input)=>{input.setAttribute('aria-label',name);const label=el('label');label.append(el('span',name),input);form.append(label);return input};
 const select=el('select');for(const v of ['sparse','normal','dense'])select.add(new Option(v,v));select.value=g.density;field('Grid density',select);const contrast=field('Grid contrast',Object.assign(el('input'),{type:'range',min:0,max:1,step:.05,value:g.contrast}));const visible=field('Show grid',Object.assign(el('input'),{type:'checkbox',checked:g.visible}));const minor=field('Show minor divisions',Object.assign(el('input'),{type:'checkbox',checked:g.minor}));
 form.oninput=()=>{c.grid={density:select.value,contrast:+contrast.value,visible:visible.checked,minor:minor.checked};changed(c)};const done=el('button','Done');done.className='primary';form.append(done);form.onsubmit=e=>{e.preventDefault();dialog.close()};const note=el('p','Applies to this chart only. Horizontal divisions stay on whole native ticks at every zoom level. The crosshair and drawing anchors snap to the exact instrument tick, including between visible grid lines.');note.className='source-note';form.append(note);dialog.append(form);document.body.append(dialog);dialog.showModal();
}
function openHistory(c){
 dialog?.remove();dialog=el('dialog');dialog.className='interval-picker';dialog.setAttribute('aria-label','Chart history / data');const head=el('div');head.className='modal-head';head.append(el('h1','History · '+chartName(c)+' · '+Intervals.label(c)));const exit=el('button','×');exit.setAttribute('aria-label','Close history settings');exit.onclick=()=>dialog.close();head.append(exit);dialog.append(head);
 const body=el('div');body.className='new-body';body.append(el('p','These settings apply to this chart only and save with your layout.'));const form=el('form');form.className='drawing-properties';const field=(name,input)=>{const l=el('label');l.append(el('span',name),input);input.setAttribute('aria-label',name);form.append(l);return input};
 const count=field('Maximum bars to load',Object.assign(el('input'),{type:'number',min:1,max:2000,step:1,value:c.historyBars||300}));const days=field('Lookback days · blank for automatic',Object.assign(el('input'),{type:'number',min:1,max:3660,step:1,value:c.historyDays||''}));const apply=el('button','Apply history settings');apply.className='primary';form.append(apply);const status=el('p');status.className='source-note';status.setAttribute('role','status');form.append(status);
 form.onsubmit=e=>{e.preventDefault();const n=Number(count.value),d=days.value?Number(days.value):null;if(!Number.isInteger(n)||n<1||n>2000||d!==null&&(!Number.isInteger(d)||d<1||d>3660)){status.textContent='Choose 1–2,000 bars and optional 1–3,660 days.';return}c.historyBars=n;c.historyDays=d;c.until=null;c.priceRange=null;syncAggregations();changed(c);dialog.close();notify('History updated for '+chartName(c)+' · '+Intervals.label(c)+' only.')};body.append(form);
 const rows=rawBarsFor(c),source=barSources.get(barRequestKey(c))||'Waiting for history';body.append(el('h3','Currently loaded'));const actual=el('p',rows.length?rows.length+' bars · '+new Date(rows[0].t*1000).toISOString().replace('T',' ')+' → '+new Date((rows.at(-1).end||rows.at(-1).t)*1000).toISOString().replace('T',' '):'No bars received for this chart yet.');actual.className='interval-source';body.append(actual,el('p',source));
 const note=el('p','The bar count is a maximum; lookback days limits how far back it may reach. Public history is capped by the provider and the available source candles (Coinbase / Hyperliquid: up to 2,400; Kraken: up to 720 per request). Larger custom bars may yield fewer final candles. Tick, volume and range history uses retained captured trades or your replay recording; historical OHLC candles cannot reconstruct individual trades. IBKR historical backfill is not yet connected. Missing history is left visible, never synthesized.');note.className='interval-source';body.append(note);dialog.append(body);document.body.append(dialog);dialog.showModal();
}
function init(){const select=$('newTimeframe');fill(select,{tf:60},false);const custom=el('input');custom.id='customNewInterval';custom.placeholder='Or type: 30s, 3h, 40R…';custom.maxLength=40;custom.setAttribute('aria-label','Custom new chart interval');select.after(custom);select.onchange=()=>{custom.value=''};}
function newSetting(){return Intervals.parse($('customNewInterval')?.value.trim()||$('newTimeframe').value,+marketTick({asset:$('instrument').value,feed:$('feed').value}))}
function prepareNew(c){fill($('newTimeframe'),c||{tf:60},false);if($('customNewInterval'))$('customNewInterval').value=''}
root.IntervalUI={mount,refresh,apply,open,openHistory,openGrid,init,newSetting,prepareNew};
})(globalThis);
