/* Recorded streams share one replay clock. The prior live desk is restored on exit. */
(() => {
 const dialog=document.createElement('dialog');dialog.id='sessionDialog';dialog.innerHTML=`<div class="modal-head"><div><div class="eyebrow">CAPTURE · REWIND · REVIEW</div><h1>Your market sessions</h1></div><button class="close" aria-label="Close sessions">×</button></div><div class="new-body"><p class="source-note">Record the actual chart feeds into local JSONL files. Select up to nine recordings to replay together on one exchange-time clock. Closing this page stops its recording.</p><div class="object-row"><button id="recordDesk" class="primary">Record this desk</button><button id="stopDeskRecording">Stop recording</button></div><p id="sessionStatus" role="status" class="source-note"></p><label for="sessionFiles">Local recordings · Ctrl/Shift to select several</label><select id="sessionFiles" multiple size="7" style="display:block;width:100%;margin:12px 0"></select><button id="loadDeskSession" class="primary">Open paused replay</button><p class="source-note">Compatible tapes need source, symbol and tick metadata. IBKR futures tapes also retain their resolved contract. Other tapes open in the advanced replay tool. Up to 100 MB / 500,000 events per session. Historical candles are not fabricated.</p></div>`;document.body.append(dialog);
 const bar=document.createElement('div');bar.id='sessionBar';bar.className='hidden';bar.innerHTML='<b id="sessionMode">REPLAY</b><button id="sessionPlay">Play</button><button id="sessionStep">Step</button><select id="sessionSpeed" aria-label="Replay speed"><option value="0.25">¼×</option><option value="0.5">½×</option><option value="1" selected>1×</option><option value="2">2×</option><option value="5">5×</option><option value="10">10×</option><option value="25">25×</option></select><input id="sessionSeek" type="range" min="0" max="1" step="0.001" value="0" aria-label="Replay position"><span id="sessionTime"></span><button id="sessionExit">Return to live</button>';document.body.append(bar);
 const entry=document.createElement('button');entry.id='sessions';entry.className='primary';entry.textContent='Record / replay in this desk';document.querySelector('#localDialog .new-body').prepend(entry);
 let current={},savedLive=null,lastMode=false;
 const send=(action,extra={})=>{if(liveSocket?.readyState===1)liveSocket.send(JSON.stringify({session:{action,...extra}}));else $('sessionStatus').textContent='Local service is offline.';};
 window.openSessions=()=>{$('localDialog').close();dialog.showModal();send('catalog');};entry.onclick=window.openSessions;
 dialog.querySelector('.close').onclick=()=>dialog.close();
 $('recordDesk').onclick=()=>send('record',{keys:[...new Set(state.charts.map(c=>c.feed+':'+c.asset))]});$('stopDeskRecording').onclick=()=>send('stop');
 $('loadDeskSession').onclick=()=>{const files=[...$('sessionFiles').selectedOptions].map(o=>o.value);if(!files.length){$('sessionStatus').textContent='Select at least one local recording.';return;}send('load',{files});};
 $('sessionPlay').onclick=()=>send(current.paused?'play':'pause');$('sessionStep').onclick=()=>send('step');$('sessionSpeed').onchange=()=>send('speed',{value:+$('sessionSpeed').value});$('sessionSeek').onchange=()=>send('seek',{value:+$('sessionSeek').value});$('sessionExit').onclick=()=>send(current.replaying?'live':'stop');
 window.sessionFault=message=>{$('sessionStatus').textContent=message;notify(message);};
 window.receiveSession=value=>{
 if(value.replaying&&current.replaying&&value.consumed<current.consumed){liveMarkets={};eventBarData.clear();FlowOverlays.clear();}current=value;window.deskReplay=!!value.replaying;document.querySelector('footer b').textContent=value.replaying?'REPLAY · READ ONLY':'MARKET DATA · READ ONLY';
 if(value.replaying&&!lastMode){clearTimeout(saveTimer);savedLive=cleanState();try{localStorage.setItem(storageKey,JSON.stringify(savedLive))}catch{}liveMarkets={};eventBarData.clear();FlowOverlays.clear();state.charts=value.streams.map(key=>{const[feed,asset]=key.split(':');return makeChart({asset,feed,contract:feed==='ibkr'?'future':feed==='hyperliquid'?'perp':'spot',ibContract:value.contracts?.[key],w:1,h:1,tf:15,count:40});});if(NativeDesk.enabled)state.charts=NativeDesk.replayCharts(state.charts);render();arrange();dialog.close();}
 if(!value.replaying&&lastMode){liveMarkets={};eventBarData.clear();FlowOverlays.clear();if(savedLive)restore(savedLive);savedLive=null;syncMarkets();}
 lastMode=value.replaying;document.getElementById('nativeReplayStream')?.classList.toggle('hidden',!value.replaying);
 if(dialog.open){const selected=new Set([...$('sessionFiles').selectedOptions].map(o=>o.value));$('sessionFiles').replaceChildren();for(const file of value.recordings){const option=document.createElement('option');option.value=file;option.textContent=file;option.selected=selected.has(file);$('sessionFiles').append(option);}}
 $('sessionStatus').textContent=value.error||((value.recording.length?'Recording '+value.recording.join(', ')+' → '+value.recordFiles.join(', '):'Recording stopped. '+value.recordings.length+' local tapes.')+' '+value.scope);
 $('recordDesk').disabled=!!value.replaying;$('stopDeskRecording').disabled=!value.recording.length;$('loadDeskSession').disabled=!value.recordings.length;
 const active=!!value.replaying||value.recording.length>0;bar.classList.toggle('hidden',!active);document.body.classList.toggle('session-active',active);$('sessionMode').textContent=value.replaying?'REPLAY · '+(value.paused?'PAUSED':'PLAYING'):'RECORDING · '+value.recording.length+' FEEDS';
 for(const id of ['sessionPlay','sessionStep','sessionSpeed','sessionSeek'])$(id).classList.toggle('hidden',!value.replaying);
 $('sessionPlay').textContent=value.paused?'Play':'Pause';$('sessionSpeed').value=value.speed;if(document.activeElement!==$('sessionSeek'))$('sessionSeek').value=value.progress;
 $('sessionTime').textContent=value.replaying?new Date(value.clock*1000).toISOString().slice(11,23)+' UTC · '+value.consumed+'/'+value.events+' events':'Local JSONL · exact captured trades';$('sessionExit').textContent=value.replaying?'Return to live':'Stop recording';state.charts.forEach(position);
 };
 window.sessionDisconnected=()=>{window.deskReplay=false;document.querySelector('footer b').textContent='MARKET DATA · READ ONLY';if(lastMode&&savedLive)restore(savedLive);savedLive=null;lastMode=false;bar.classList.add('hidden');document.body.classList.remove('session-active');};
})();
