/* Local order-ticket planning. No order transport, account secrets, or simulated balances. */
(function(root){
'use strict';
const panels=new WeakMap(),el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n};
function quote(c){const m=marketFor(c),fresh=m?.connected&&m.status==='receiving'&&Number.isFinite(m.bookAge)&&m.bookAge+(Number.isFinite(m.clientReceived)?Math.max(0,Date.now()-m.clientReceived)/1000:0)<=15;const bid=fresh?m.book?.bids?.[0]:null,ask=fresh?m.book?.asks?.[0]:null;return{m,bid,ask,fresh:!!bid&&!!ask}}
// Quote shortcuts take a price snapshot. They never submit or chase an order.
function quoteChoice(side,at,q){if(!['buy','sell'].includes(side)||!['bid','ask'].includes(at)||!q?.fresh)return null;const raw=q[at]?.[0];if(raw==null||String(raw).trim()==='')return null;const value=Number(raw);return Number.isFinite(value)?{side,kind:'limit',price:value}:null}
function referencePrice(kind,fields,q,side){if(['limit','stop-limit','stop'].includes(kind)){const raw=kind==='stop'?fields.stop:fields.limit;if(raw==null||String(raw).trim()==='')return null;const value=Number(raw);return Number.isFinite(value)?value:null}return quoteChoice(side,side==='buy'?'ask':'bid',q)?.price??null}
function valid(d){return d&&d.mode==='LOCAL_DRAFT'&&typeof d.symbol==='string'&&d.symbol.length<=80&&typeof d.source==='string'&&d.source.length<=100&&['buy','sell'].includes(d.side)&&['market','limit','stop','stop-limit'].includes(d.kind)&&['DAY','GTC','IOC','FOK'].includes(d.tif)&&Number.isFinite(d.quantity)&&d.quantity>0&&d.quantity<=10000000&&Number.isFinite(d.created)&&d.created>0&&['limit','stop','stopLoss','target'].every(k=>d[k]===null||Number.isFinite(d[k]))}
function toggle(c){c.tradePanelOpen=!c.tradePanelOpen;const tile=$('chart-'+c.id);tile?.classList.toggle('trade-open',c.tradePanelOpen);tile?.querySelector('.trade-toggle')?.setAttribute('aria-pressed',String(c.tradePanelOpen));if(c.tradePanelOpen)refresh(c);changed(c)}
function mount(c,tile){
 const toggleButton=el('button','Trade');toggleButton.className='trade-toggle';toggleButton.title='Show / hide trading panel';toggleButton.setAttribute('aria-label','Trading panel for '+chartName(c));toggleButton.setAttribute('aria-pressed',String(!!c.tradePanelOpen));toggleButton.onclick=()=>{focus(c);toggle(c)};tile.querySelector('.actions').prepend(toggleButton);
 const panel=el('aside');panel.className='trade-panel';panel.setAttribute('aria-label','Trading panel · '+chartName(c));const head=el('div');head.className='trade-panel-head';head.append(el('strong','Trading'));const exit=el('button','×');exit.setAttribute('aria-label','Close trading panel');exit.onclick=()=>toggle(c);head.append(exit);panel.append(head);
 const badge=el('span','DRAFT ONLY');badge.className='trade-mode';badge.title='Local tickets only · broker execution is not connected';head.insertBefore(badge,exit);const accountLabel=el('label');accountLabel.className='ticket-account';const account=el('select');account.setAttribute('aria-label','Trading account');account.add(new Option('Local draft','draft'));account.add(Object.assign(new Option('Live broker execution · unavailable','live'),{disabled:true}));account.add(Object.assign(new Option('Paper broker account · unavailable','paper'),{disabled:true}));accountLabel.append(account);panel.append(accountLabel);
 const metrics=el('dl');metrics.className='trade-metrics';for(const label of ['Equity','Buying power','Available margin','Realized P&L','Unrealized P&L','Position']){metrics.append(el('dt',label),el('dd','—'))}panel.append(metrics);const accountNote=el('p','Account balances and positions require an execution/account adapter. The current IBKR integration is read-only market data.');accountNote.className='trade-note';panel.append(accountNote);
 const book=el('div');book.className='ticket-book';const bid=el('div'),ask=el('div');bid.className='ticket-bid';ask.className='ticket-ask';bid.append(el('small','BID'));ask.append(el('small','ASK'));const bidValue=el('strong','—'),askValue=el('strong','—');bid.append(bidValue);ask.append(askValue);book.append(bid,ask);panel.append(book);const spread=el('p');spread.className='trade-note ticket-spread';panel.append(spread);
 const tabs=el('div');tabs.className='trade-tabs';tabs.setAttribute('role','tablist');const ticketTab=el('section'),accountTab=el('section'),activityTab=el('section');const sections=[ticketTab,accountTab,activityTab];for(const [i,label] of ['Ticket','Account','Activity'].entries()){const b=el('button',label);b.type='button';b.setAttribute('role','tab');b.id='ticket-tab-'+c.id+'-'+i;b.tabIndex=i===0?0:-1;b.setAttribute('aria-controls','ticket-pane-'+c.id+'-'+i);sections[i].id='ticket-pane-'+c.id+'-'+i;sections[i].setAttribute('role','tabpanel');sections[i].setAttribute('aria-labelledby',b.id);b.setAttribute('aria-selected',String(i===0));b.onclick=()=>{sections.forEach((section,j)=>section.hidden=j!==i);for(const [j,button]of [...tabs.children].entries()){button.setAttribute('aria-selected',String(j===i));button.tabIndex=j===i?0:-1}};b.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowRight'?1:2))%3;tabs.children[next].click();tabs.children[next].focus()};tabs.append(b)}panel.insertBefore(tabs,accountLabel);accountTab.append(metrics,accountNote);accountTab.hidden=true;activityTab.hidden=true;ticketTab.append(book,spread);panel.append(ticketTab,accountTab,activityTab);
 const shortcuts=el('div');shortcuts.className='ticket-shortcuts';shortcuts.setAttribute('role','group');shortcuts.setAttribute('aria-label','Prepare a limit ticket at bid or ask');ticketTab.append(shortcuts);const quoteButtons=[];
 const form=el('form');form.className='ticket-form';const inputs={};function field(label,input){const l=el('label',label);input.setAttribute('aria-label',label);l.append(input);form.append(l);return input}function select(label,values){const n=el('select');for(const [v,t]of values)n.add(new Option(t,v));return field(label,n)}
 inputs.side=select('Side',[['buy','Buy / long'],['sell','Sell / short']]);inputs.kind=select('Order type',[['market','Market'],['limit','Limit'],['stop','Stop market'],['stop-limit','Stop limit']]);inputs.quantity=field(c.feed==='ibkr'?'Contracts':'Quantity',Object.assign(el('input'),{type:'number',min:c.feed==='ibkr'?1:.00000001,max:10000000,step:c.feed==='ibkr'?1:'any',value:c.feed==='ibkr'?1:.01}));inputs.tif=select('Time in force',[['DAY','Day'],['GTC','Good till cancelled'],['IOC','Immediate or cancel'],['FOK','Fill or kill']]);
 for(const [key,name]of [['limit','Limit price'],['stop','Trigger price'],['stopLoss','Bracket stop loss'],['target','Bracket take profit']])inputs[key]=field(name,Object.assign(el('input'),{type:'text',inputMode:'decimal',placeholder:key==='stopLoss'||key==='target'?'Optional':'Exact price'}));
 const advanced=el('details');advanced.className='ticket-advanced';advanced.append(el('summary','Bracket / time in force'));const advancedFields=el('div');advancedFields.className='ticket-advanced-fields';advancedFields.append(inputs.tif.parentElement,inputs.stopLoss.parentElement,inputs.target.parentElement);advanced.append(advancedFields);form.append(advanced);
 const notional=el('p');notional.className='ticket-notional';form.append(notional);const save=el('button','Save draft');save.className='primary';save.type='submit';form.append(save);const status=el('p');status.className='trade-note';status.setAttribute('role','status');form.append(status);ticketTab.append(form);
 const orders=el('details');orders.open=true;orders.append(el('summary','Saved local tickets'));const drafts=el('div');orders.append(drafts);activityTab.append(orders);const positions=el('details');positions.append(el('summary','Broker orders & positions'),el('p','Unavailable until an account/execution adapter is connected. Saved tickets above are local drafts, not submitted orders.'));activityTab.append(positions);
 const foot=el('p','Broker execution not connected. No orders are sent.');foot.className='trade-note ticket-footer';ticketTab.append(foot);tile.append(panel);tile.classList.toggle('trade-open',!!c.tradePanelOpen);
 const item={panel,inputs,bidValue,askValue,quoteButtons,spread,notional,drafts,status};panels.set(c,item);
 function kindState(){inputs.limit.parentElement.hidden=!['limit','stop-limit'].includes(inputs.kind.value);inputs.stop.parentElement.hidden=!['stop','stop-limit'].includes(inputs.kind.value);inputs.limit.disabled=!['limit','stop-limit'].includes(inputs.kind.value);inputs.stop.disabled=!['stop','stop-limit'].includes(inputs.kind.value);refresh(c)}inputs.kind.onchange=()=>{status.textContent='';kindState()};inputs.side.onchange=()=>{status.textContent='';refresh(c)};inputs.quantity.oninput=()=>refresh(c);inputs.limit.oninput=()=>refresh(c);inputs.stop.oninput=()=>refresh(c);
 for(const [side,at,label]of [['buy','bid','Buy Bid'],['sell','ask','Sell Ask'],['buy','ask','Buy Ask'],['sell','bid','Sell Bid']]){const button=el('button',label);button.type='button';button.className='ticket-'+side;button.title='Prepare '+side+' limit at the current '+at+' · does not submit';button.onclick=()=>{const choice=quoteChoice(side,at,quote(c));if(!choice){status.textContent='Wait for a fresh bid and ask.';return}inputs.side.value=choice.side;inputs.kind.value=choice.kind;inputs.limit.value=String(snap(choice.price,+marketTick(c)));status.textContent=label+' selected · local limit ticket.';kindState()};quoteButtons.push(button);shortcuts.append(button)}
 form.onsubmit=e=>{e.preventDefault();const tick=+marketTick(c),draft={mode:'LOCAL_DRAFT',symbol:chartName(c),source:c.feed+':'+c.asset,created:Date.now(),side:inputs.side.value,kind:inputs.kind.value,tif:inputs.tif.value,quantity:Number(inputs.quantity.value)};try{for(const key of ['limit','stop','stopLoss','target']){const f=inputs[key],needed=key==='limit'&&['limit','stop-limit'].includes(draft.kind)||key==='stop'&&['stop','stop-limit'].includes(draft.kind);if(needed&&!f.value.trim())throw Error('Enter an exact '+key+' price.');draft[key]=!f.disabled&&f.value.trim()?Number(f.value):null;if(draft[key]!==null&&(!Number.isFinite(draft[key])||c.feed!=='ibkr'&&draft[key]<=0||Math.abs(draft[key]-snap(draft[key],tick))>tick*1e-6))throw Error('Prices must align with the native tick: '+tick)}if(!valid(draft)||c.feed==='ibkr'&&!Number.isInteger(draft.quantity))throw Error('Check quantity and ticket fields.');const entry=draft.kind==='limit'||draft.kind==='stop-limit'?draft.limit:draft.kind==='stop'?draft.stop:null;if(entry!==null){if(draft.stopLoss!==null&&(draft.side==='buy'?draft.stopLoss>=entry:draft.stopLoss<=entry))throw Error('A long bracket stop must be below entry; a short stop above.');if(draft.target!==null&&(draft.side==='buy'?draft.target<=entry:draft.target>=entry))throw Error('A long target must be above entry; a short target below.')}if((c.orderDrafts||[]).length>=20)throw Error('Keep up to 20 local tickets per chart; remove an older draft first.');(c.orderDrafts??=[]).push(draft);status.textContent='Local ticket saved. Nothing was sent to a broker.';list(c);saveSoon()}catch(error){status.textContent=error.message}};
 kindState();list(c);refresh(c);
}
function list(c){const area=panels.get(c)?.drafts;if(!area)return;area.replaceChildren();if(!c.orderDrafts?.length){area.append(el('p','No local tickets saved.'));return}for(const d of [...c.orderDrafts].reverse()){const row=el('div');row.className='ticket-draft';row.append(el('strong',d.side.toUpperCase()+' '+d.quantity+' · '+d.symbol),el('small',d.kind+' · '+d.tif+(d.limit!==null?' · limit '+d.limit:'')+(d.stop!==null?' · trigger '+d.stop:'')+' · '+d.source));const remove=el('button','Remove draft');remove.onclick=()=>{c.orderDrafts=c.orderDrafts.filter(v=>v!==d);list(c);saveSoon()};row.append(remove);area.append(row)}}
function refresh(c){const p=panels.get(c);if(!p||!c.tradePanelOpen)return;const q=quote(c),tick=+marketTick(c);p.bidValue.textContent=q.bid?price(Number(q.bid[0]),c):'—';p.askValue.textContent=q.ask?price(Number(q.ask[0]),c):'—';for(const button of p.quoteButtons)button.disabled=!q.fresh;p.spread.textContent=q.fresh?'Spread '+price(Number(q.ask[0])-Number(q.bid[0]),c)+' · '+Math.round((Number(q.ask[0])-Number(q.bid[0]))/tick)+' ticks':'Fresh bid / ask unavailable';const qty=Number(p.inputs.quantity.value),reference=referencePrice(p.inputs.kind.value,{limit:p.inputs.limit.value,stop:p.inputs.stop.value},q,p.inputs.side.value),multiplier=c.feed==='ibkr'?Number(c.ibContract?.multiplier):1;const total=Number.isFinite(reference)&&qty>0&&multiplier>0?Math.abs(reference*qty*multiplier):null;p.notional.textContent=total!==null?'Notional ≈ '+total.toLocaleString('en-US',{maximumFractionDigits:2})+' '+(c.ibContract?.currency||'USD')+' · before fees':'Notional —';}
root.TradePanel={mount,refresh,valid};if(typeof module!=='undefined'&&module.exports)module.exports={valid,quoteChoice,referencePrice};
})(globalThis);
